(define/contract (max-uncrossed-lines nums1 nums2)
  (-> (listof exact-integer?) (listof exact-integer?) exact-integer?)
    (define dp (make-list (add1 (length nums1)) 0))
    (define cur 0)
    (for ([n nums2])
      (set! cur 0)
      (set! dp
        (cons 0 (map (lambda (m)
               (set! cur (max cur m))
               cur
             )
         (for/list ([m nums1] [d1 dp] [d2 (cdr dp)])
           (if (= m n)
             (max d2 (add1 d1))
             (max d2 d1)))
         )
        )
      )
      (println dp)
    )
    (last dp)
  )
