(define/contract (kth-largest-value matrix k)
  (-> (listof (listof exact-integer?)) exact-integer? exact-integer?)
  (define n (length (car matrix)))
  (define ans (make-vector (* (add1 (length matrix)) (add1 n)) 0))
  (for ([i (range (length matrix))] [line matrix])
    (for ([j (range (length line))] [number line])
      (vector-set! ans (+ (* (add1 i) (add1 n)) (add1 j))
                   (bitwise-xor number
                                (vector-ref ans (+ (* i (add1 n)) j))
                                (vector-ref ans (+ (* (add1 i) (add1 n)) j))
                                (vector-ref ans (+ (* i (add1 n)) (add1 j))))
      )
    )
  )
  (vector-ref (vector-sort ans >) (sub1 k))
)
